### ISSUE TITLE
java.lang.IllegalStateException: Result is already complete: succeeded

### ISSUE THREAD

**Issue by jincieryi** [sczyh30/vertx-blueprint-microservice#10]
你好，非常感谢提供的vertx系列向导教程。有个问题想请教下，我模仿TODO为microservice添加测试用例执行tearDown中close方法时报错Result is already complete: succeeded。实际debug发现BaseMicroserviceVerticle中的stop方法被调用了两遍。

@After
	public void tearDown(TestContext context) {
		vertx.close(context.asyncAssertSuccess());
	}

提示异常：
[vert.x-eventloop-thread-0] 2016-11-07T08:42:09.981+08:00 SEVERE [io.vertx.core.impl.ContextImpl]  Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jincieryi** [comment]
好像是3.3的一个bug https://github.com/eclipse/vert.x/issues/1625

**Comment by sczyh30** [comment]
Yes, this is related to eclipse/vert.x#1625. You can refer to it for guidelines.
