### ISSUE TITLE
ClassNotFoundException XXXVertxProxyHandler

### ISSUE THREAD

**Issue by AlexBischof** [sczyh30/vertx-blueprint-microservice#28]
Hi,
if you build the repo with maven and then start one of the fat-jars (e.g. `java -jar account-microservice-fat.jar -conf ../src/config/local.json`) it lead to the following stacktrace.

The problem is that the generated-folders are **not** included in the _fat-jar_. What is best practice here?

`java.lang.IllegalStateException: Cannot find proxyClass: io.vertx.blueprint.microservice.account.AccountServiceVertxProxyHandler
	at io.vertx.serviceproxy.ProxyHelper.loadClass(ProxyHelper.java:104)
	at io.vertx.serviceproxy.ProxyHelper.registerService(ProxyHelper.java:78)
	at io.vertx.serviceproxy.ProxyHelper.registerService(ProxyHelper.java:71)
	at io.vertx.serviceproxy.ProxyHelper.registerService(ProxyHelper.java:65)
	at io.vertx.blueprint.microservice.account.UserAccountVerticle.start(UserAccountVerticle.java:30)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.vertx.blueprint.microservice.account.AccountServiceVertxProxyHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.serviceproxy.ProxyHelper.loadClass(ProxyHelper.java:102)
	... 11 more`

**Comment by sczyh30** [comment]
Hi, I've reproduced this problem. This is related to the update of `maven-compiler-plugin`. Please downgrade the `maven-compiler-plugin` version from **3.6.1** to **3.1** temporarily (in `pom.xml`). I'll check the detailed changes of the plugin and update the configurations.

**Comment by somnath157** [comment]
facing the same Issue i am using 
Gradle version : 6.3
var vertxVersion = '3.9.0'
        compile group: 'io.vertx', name: 'vertx-core', version: vertxVersion
        compile group: 'io.vertx', name: 'vertx-service-discovery', version: vertxVersion
        compile group: 'io.vertx', name: 'vertx-web-api-contract', version: vertxVersion
        compile group: 'io.vertx', name: 'vertx-web-client', version: vertxVersion
        compile group: 'io.vertx', name: 'vertx-hazelcast', version: vertxVersion
        compile group: 'io.vertx', name: 'vertx-circuit-breaker', version: vertxVersion
        compile group: 'io.vertx', name: 'vertx-service-proxy', version: vertxVersion
        compileOnly group: 'io.vertx',name: 'vertx-codegen',version: vertxVersion
